### PR TITLE
Frontend stuff

### PR DESCRIPTION
**Pull request by donnelldebnam**
In this PR I added some things to the Home page and a simple banner to the about page. This should almost conclude the UI stuff that doesn't involve our actual features.

### CODE REVIEW

**Comment by anthony23334** [comment]
@donnelldebnam quick question, IS there a way you can lower the blurriness of the homepage photo. It will be nice to see a little bit of what was behind the letters (just a little bit). Or you can display the whole picture as the user scrolls

**Comment by donnelldebnam** [comment]
@anthony23334 Thanks! And yeah, I blurred it cause I remember JW mentioning the visibility of the words that are over the photo. I can probably blur it less so that both are visible

**Comment by anthony23334** [comment]
@donnelldebnam , another suggestion: you can also talk about the emoji stuff as a "unique feature"

**Comment by anthony23334** [comment]
@donnelldebnam , i noticed that whenever I am using a smaller screen (phone) the words are disappearing, which is good; in that case, the photo should go back to full display (no blur). But right now, it looks like this: 
screen shot 2018-07-15 at 6 58 45 pm
](url)

**Comment by jiayiw6** [comment]
@donnelldebnam OMG this is so great, I love the texture of the image and the "unique feature" list. Well done! This is super awesome!

**Comment by donnelldebnam** [comment]
@jiayiw6 thank you!!

**Pull request merged**
