### PR TITLE
Chat interface

### PR DESCRIPTION
**Pull request by donnelldebnam**
Working on an iMessage-like interface for chat messages... let me know what you-all think!

Still need to add:
*     compatibility for JavaScript delete features
*     spacing fixes for messages
*     possible chat-photo feature

Should I follow up with this?

### CODE REVIEW

**Comment by jiayiw6** [comment]
@donnelldebnam Hey Donnell, this looks super nice! Just one quick question: [https://imgur.com/a/akYhxuz](url) Is this intended for the chat bubbles to go horizontally or am I doing something wrong? thanks!

**Comment by donnelldebnam** [comment]
@jiayiw6 Hey, no a lot of it got messed up when I was trying to add things and had to commit unfinished changes and a bunch of other stuff. If you guys think it’ll be a good thing to add I’ll go in and fix it up. I just left it alone cause I wasnt sure

**Comment by jiayiw6** [comment]
@donnelldebnam Oh okay! Sorry, I thought it's awaiting reviews XD I think it would be a good add since it different us from the other chat apps, you have really cool ideas for the front end btw!

**Comment by donnelldebnam** [comment]
@jiayiw6 No problem, and thanks! PR #88 is approved already but I wanna make sure you saw it before I merge. Could you check that one out too please?

**Comment by jiayiw6** [comment]
@donnelldebnam Ok! I will do that right now! Thanks!

**Pull request closed without merging**
