### PR TITLE
Style Tags' Tests

### PR DESCRIPTION
**Pull request by sarojbhatta**

### CODE REVIEW

**Comment by donnelldebnam** [comment]
I guess it's not a valid tag then it could just be considered characters that are intended to be printed as plain text... I wouldn't worry about it!

**Comment by donnelldebnam** [comment]
> I see. I will look into it. But not only for the capital tags, the program is returning the actual text for Invalid tags also. I am returning both Capital and Invalid tags as they are input just in case users want to use those kind of letter combination (which we call tags for our program) and to print those tag-things in the actual message. How should we proceed? By removing invalid/capital tags or by printing?

Yeah so it seems that if the tag is invalid, it should just be accepted as regular text and just print as it is. I don't think you should worry about creating a way to handle it.

**Comment by donnelldebnam** [comment]
> I see. I will look into it. But not only for the capital tags, the program is returning the actual text for Invalid tags also. I am returning both Capital and Invalid tags as they are input just in case users want to use those kind of letter combination (which we call tags for our program) and to print those tag-things in the actual message. How should we proceed? By removing invalid/capital tags or by printing?

**Comment by sarojbhatta** [comment]
Okay, cool. I will merge it to the master once it gets approved by anyone of you. Thank you.

**Pull request merged**
